# Generated by Django 4.2.7 on 2023-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book name')),
                ('page_count', models.CharField(max_length=255, verbose_name='Count of page')),
                ('author', models.CharField(max_length=255, verbose_name='Author of book')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('name',),
            },
        ),
    ]
